//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment11_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public string Engine { get; set; }
        public decimal Doors { get; set; }
        public string Style { get; set; }
        public string VIN { get; set; }
        public string Color { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
